export const DATA_REQUEST = "Data_REQUEST"
export const DATA_SUCCESS = "Data_SUCCESS"
export const DATA_FAILED = "Data_FAILED"
export const SAVE_DATA = "SAVE_DATA"
export const DATA_INFO = "DATA_INFO"
export const UPDATE_DATA = "UPDATE_DATA"
export const CREATE_DATA = "CREATE_DATA"
export const DELETE_DATA = "DELETE_DATA"
